### ISSUE TITLE
 Preparing product data for marks 

### ISSUE THREAD

**Issue by brad0351** [brad0351/ecommerce-pattern-library#5]
@thomasjbradley, I've completed the preparing product data task.

**Comment by thomasjbradley** [comment]
It’s not working when I try to go view one of the products:
https://tender-darwin-f134b9.netlify.com/products/boxes/

Probably the typos here:
https://github.com/brad0351/ecommerce-pattern-library/blob/master/_config.yml#L32-L36
Replace with this:

```yml
defaults:
  - scope:
      path: _products
    values:
      layout: product
```
